### ISSUE TITLE
WooCommerce Bookings - Calendar Performance Bug

### ISSUE THREAD

**Issue by MCKLtech** [woocommerce/woocommerce-bookings-generator#1]
As an FYI to anyone using WooBookings with a large data set, I've noticed (what I think) is a significant performance bug in the page calendar.

It stems from the AJAX call to **wc_ajax_wc_bookings_find_booked_day_blocks** in **class-wc-bookings-wc-ajax.php**

If you monitor the network tab in Chrome, you'll see the time strings have the format of:

_Tue Nov 06 2018 00:00:00 GMT-0800 (PST)_

This is sent into a strtotime() that doesn't have a hope of decoding it, and if often fails. The result is a full-blown search for availability over a massive range, causing major site slow down. If you want to see what I mean, look at the JSON payload that is returned, it often has bookings in the past and for the next year into the future.

Of the off chance any Automatic Devs cruise this forum, it may be worth taking a look at as we're having to continually patch poor performance in WooBookings and it's like a brick wall talking to your regular support.

**Comment by jessepearson** [comment]
@MCKLtech Sorry for the late reply here, this repo wasn't monitored for issues by anyone (I've just added myself to follow along). 

The dev team is working on a lot of updates for Bookings to try to alleviate the issues with slow calendars. Releases should be coming out later this year with fixes.

**Comment by philthebass** [comment]
I'm having a similar issue.
![Screenshot 2023-11-13 at 11 01 53](https://github.com/woocommerce/woocommerce-bookings-generator/assets/13836637/ec9c3ca9-b8f4-4d3c-aea2-2f251b773166)

Does anyone have any suggestions for improving this?

Thanks

**Comment by MCKLtech** [comment]
It's been a while since I looked at this particular code but we patched it after every update to handle the search better. The reality is that WC Bookings simply does not scale, it's fine for a small business or B&B, but if you are dealing with thousands of bookings, it's basically useless.

Redis and other caching options help immensely too.

**Comment by philthebass** [comment]
> It's been a while since I looked at this particular code but we patched it after every update to handle the search better. The reality is that WC Bookings simply does not scale, it's fine for a small business or B&B, but if you are dealing with thousands of bookings, it's basically useless.
> 
> Redis and other caching options help immensely too.

Thanks - we'll look at other caching options
